# 1.

In [2]:
import numpy as np

In [6]:
def altSum(arr):
    sumEle=0
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if (i+j)% 2==0:
                sumEle+=arr[i][j]
    return sumEle
row=int(input("enter row:"))
column=int(input("enter columns:"))
arr=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr[i][j]=int(input())
        
sumEle=altSum(arr)
print("alternate sum: ", sumEle)

enter row:2
enter columns:3
enter elements row wise:
1
2
3
4
5
6
alternate sum:  9


# 2

In [7]:
def evenval(arr1):
    lst=[]
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j]%2==0:
                lst.append(arr[i][j])
                
    return lst
row=int(input("enter row:"))
column=int(input("enter columns:"))
arr=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr[i][j]=int(input())
        
lst=evenval(arr)
print("even value: ", lst)
    

enter row:2
enter columns:2
enter elements row wise:
1
2
3
4
even value:  [2, 4]


# 3

In [8]:
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def find_primes(arr):
    primes = []
    for row in arr:
        for num in row:
            if is_prime(num):
                primes.append(num)
    return primes
row=int(input("enter row:"))
column=int(input("enter columns:"))
arr=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr[i][j]=int(input())
        
prime=find_primes(arr)
print(prime)
        

enter row:2
enter columns:3
enter elements row wise:
1
2
3
4
5
6
[2, 3, 5]


# 4.

In [23]:
arr = np.random.randint(0, 10, size=(5, 5))
def maxval(arr):
    lst=[]
    for i in range(5):
        lst.append(np.max(arr[i]))
    return lst
print(arr)
print("max value ", lst)

[[6 8 2 0 7]
 [5 7 0 2 7]
 [1 6 0 1 9]
 [3 9 8 2 2]
 [0 1 7 0 7]]
max value  [6, 7, 8, 5, 7]


In [13]:
print(np.random.randint(5))

2


# 5.

In [10]:
def cornEle(arr):
    lst=[]
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if i!=0 and j!=0 and i!=row-1 and j!=column-1:
                lst.append(arr[i][j])
    return lst

row=int(input("enter row:"))
column=int(input("enter columns:"))
arr=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr[i][j]=int(input())
        
cornEle=cornEle(arr)
print(arr)
print(cornEle)



enter row:4
enter columns:4
enter elements row wise:
1
2
3
4
1
2
3
4
1
2
3
4
4
3
2
1
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [4 3 2 1]]
[2, 3, 2, 3]


# 6.

In [18]:
def comEle(arr1,arr2):
    return np.intersect1d(arr1,arr2)

row=int(input("enter row:"))
column=int(input("enter columns:"))
arr1=np.zeros((row,column),int)
arr2=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr1[i][j]=int(input())
        arr2[i][j]=int(input())
        
cornEle=comEle(arr1,arr2)
print(arr1,arr2)
print(cornEle)

enter row:1
enter columns:1
enter elements row wise:



ValueError: invalid literal for int() with base 10: ''

# 7.

In [21]:
def thresh(arr):
    thrval=int(input())
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j]>=thrval:
                arr[i][j]=thrval
                
    return arr
                

row=int(input("enter row:"))
column=int(input("enter columns:"))
arr=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr[i][j]=int(input())
        
thresh1=thresh(arr)
print(arr)
print(thresh1)

enter row:2
enter columns:2
enter elements row wise:
1
2
3
4
2
[[1 2]
 [2 2]]
<function thresh at 0x7fc96141aa60>


# 8.

In [26]:
def sumDig(arr):
    sum=0
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if j<i:
                sum+=arr[i][j]
                
    return sum
                

row=int(input("enter row:"))
column=int(input("enter columns:"))
arr=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr[i][j]=int(input())
        
sumDig=sumDig(arr)
print(arr)
print(sumDig)

enter row:3
enter columns:3
enter elements row wise:
1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
19


# 9.

# 10.

In [28]:
def count_unique(arr):
    frequency_dict = {}
    for row in arr:
        for element in row:
            if element in frequency_dict:
                frequency_dict[element] += 1
            else:
                frequency_dict[element] = 1
    return frequency_dict

row=int(input("enter row:"))
column=int(input("enter columns:"))
arr=np.zeros((row,column),int)
print("enter elements row wise:")
for i in range(row):
    for j in range(column):
        arr[i][j]=int(input())
        
count_unique=count_unique(arr)
print(arr)
print(count_unique)

enter row:3
enter columns:3
enter elements row wise:
1
2
3
4
5
6
2
1
3
[[1 2 3]
 [4 5 6]
 [2 1 3]]
{1: 2, 2: 2, 3: 2, 4: 1, 5: 1, 6: 1}
