In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
print(arr1.itemsize)
print(arr2.dtype)
print(arr1.ndim)
print(arr1.size)
print(arr2.size)
print(arr1.nbytes)
print(arr1.shape)
print(arr2.shape)

8
int64
1
5
6
40
(5,)
(2, 3)


In [6]:
arr1=np.arange(5)
arr2=np.arange(5)
print(arr1==arr2)
print(id(arr1)==id(arr2))

[ True  True  True  True  True]
False


# Methods to create 2d arrays#

In [8]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1.shape)
print(arr1.ndim)

(2, 3)
2


In [10]:
for i in range(len(arr1)):
    for j in range(len(arr1[i])):
        print(arr1[i][j],end=" ")
    print()

1 2 3 
4 5 6 


In [13]:
arr2=np.zeros((2,2),int)
print(arr2)

[[0 0]
 [0 0]]


In [18]:
arr3=np.ones((2,2,3),int)
print(arr3)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [23]:
arr4=np.eye(3,dtype=int)
print(arr4)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [30]:
arr5=np.full((2,3),"|")
arr5

array([['|', '|', '|'],
       ['|', '|', '|']], dtype='<U1')

In [35]:
arr=np.reshape(arr1,(2,3))
print(arr)

[[1 2 3]
 [4 5 6]]


# Matrix using numpy

In [37]:
print(arr4.diagonal())
print(np.diagonal(arr4))

[1 1 1]
[1 1 1]


In [38]:
print(arr4.transpose())

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [39]:
print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [40]:
arr.sum()

21

In [41]:
print(arr.min())
print(arr.max())

1
6
